Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.frontendBucketName}
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: ${self:custom.frontendBucketName}
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: s3:GetObject
            Resource: "arn:aws:s3:::${self:custom.frontendBucketName}/*"
            Principal: "*"


