service: jd-backend

provider:
  name: aws
  runtime: python3.9
  region: eu-west-1
  stage: dev
  environment:
    COGNITO_USER_POOL_ID: eu-west-1_J3SXFvZbW

functions:
  signup:
    handler: user_signup.signup
    events:
      - http:
          path: signup
          method: post
          cors: true
plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    slim: true
  serverless-offline:
    httpPort: 4000