service: jd-backend

provider:
  name: aws
  runtime: python3.9
  region: eu-west-1
  stage: dev
  environment:
    COGNITO_USER_POOL_ID: eu-west-1_J3SXFvZbW

functions:
  signup:
    handler: user_signup.signup
    timeout: 10 # Increase the timeout value in seconds as needed
    events:
      - http:
          path: signup
          method: post
          cors: true
plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-dynamodb-local

custom:
  pythonRequirements:
    slim: true
  serverless-offline:
    httpPort: 4000
  dynamodb:
    start:
      port: 8000
      inMemory: false
      dbPath: null
      sharedDb: true
      delayTransientStatuses: false
      cors: null

resources:
  Resources:

    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: JD_User
        AttributeDefinitions:
          - AttributeName: UserId
            AttributeType: S
        KeySchema:
          - AttributeName: UserId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

