service: jd-backend

provider:
  name: aws
  runtime: python3.9
  region: eu-west-1
  stage: dev
  environment:
    COGNITO_USER_POOL_ID: eu-west-1_J3SXFvZbW

functions:
  - ${file(login-functions.yml)}
#  - ${file(application-functions.yml)}

plugins:
  # for front end
  - serverless-finch
  - serverless-s3-sync

  # for lambda
  - serverless-python-requirements

  # for testing locally
  - serverless-offline
  - serverless-dynamodb-local

custom:
  frontendBucketName: jobsearchdashboard.com
  client:
    bucketName: ${self:custom.frontendBucketName}
    distributionFolder: ../frontend/build
  s3Sync:
    - bucketName: ${self:custom.frontendBucketName}
      localDir: ../frontend/build
  pythonRequirements:
    slim: true
  serverless-offline:
    httpPort: 4000
  dynamodb:
    start:
      port: 8000
      inMemory: false
      dbPath: null
      sharedDb: true
      delayTransientStatuses: false
      cors: null


resources:
  - ${file(database-s3-resources.yml)}
  - ${file(s3-resources.yml)}
  - ${file(login-s3-resources.yml)}
#  - ${file(application-s3-resources.yml)}
