# Add the User Pool resource definition
CognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: JobSearchUserPool
    # Set up the password policy
    Policies:
      PasswordPolicy:
        MinimumLength: 8
        RequireUppercase: true
        RequireLowercase: true
        RequireNumbers: true
        RequireSymbols: true
    Schema:
      - Name: name
        AttributeDataType: String
        Mutable: true
        Required: true
      - Name: email
        AttributeDataType: String
        Mutable: false
        Required: true
      # Add more custom attributes if needed
    UsernameAttributes:
      - email
    AutoVerifiedAttributes:
      - email