service: jobsearch-dashboard

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: eu-west-1

plugins:
  - serverless-offline
  - serverless-dynamodb-local

resources:
  # Include the nested CloudFormation stack
  - ${file(./dynamodb-tables.yml)}
  - ${file(./cognito-user-pool.yml)}
